server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:static/
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.12.151.133:1521:orcl
    username: testuser2
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xa.fourth_p.pojo

